spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

bot.client.username=botClientForLaba7
bot.client.token=8749551950:AAFqV10greeyuk9PJXpZiJfLgPElPCvSgdU

bot.agent.username=botAgentForLaba7
bot.agent.token=8631430842:AAE6qVE5IGcrPp2Y0OnNYPrSwKrXsoGjZoY
bot.agent.admin-chat-id=749566966